"""initial planner state schema

Revision ID: 4162ba38a257
Revises: 
Create Date: 2026-10-08 23:04:54.575440
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4162ba38a257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_states',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_planner_states_version_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('end_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('start_timestamp_microseconds < end_timestamp_microseconds', name='ck_calendar_events_valid_interval'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id')
    )
    op.create_table('constraints',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('constraint_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('start_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('end_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('start_timestamp_microseconds < end_timestamp_microseconds', name='ck_constraints_valid_interval'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'constraint_id')
    )
    op.create_table('goals',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline_timestamp_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id')
    )
    op.create_table('plans',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('date_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('planning_horizon_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('planning_horizon_microseconds > 0', name='ck_plans_horizon_positive'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id'),
    sa.UniqueConstraint('state_id', name='uq_plans_one_per_state')
    )
    op.create_table('tasks',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('scheduling_status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('estimated_duration_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('deadline_timestamp_microseconds', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('parent_task_id', sa.Text(), nullable=True),
    sa.CheckConstraint('estimated_duration_microseconds >= 0', name='ck_tasks_duration_nonnegative'),
    sa.CheckConstraint('parent_task_id IS NULL OR parent_task_id <> id', name='ck_tasks_not_own_parent'),
    sa.ForeignKeyConstraint(['state_id', 'parent_task_id'], ['tasks.state_id', 'tasks.id'], name='fk_tasks_parent_same_state'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id')
    )
    op.create_table('dependencies',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('dependent_task_id', sa.Text(), nullable=False),
    sa.Column('prerequisite_task_id', sa.Text(), nullable=False),
    sa.CheckConstraint('dependent_task_id <> prerequisite_task_id', name='ck_dependencies_not_self_referential'),
    sa.ForeignKeyConstraint(['state_id', 'dependent_task_id'], ['tasks.state_id', 'tasks.id'], name='fk_dependencies_dependent_same_state'),
    sa.ForeignKeyConstraint(['state_id', 'prerequisite_task_id'], ['tasks.state_id', 'tasks.id'], name='fk_dependencies_prerequisite_same_state'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'dependent_task_id', 'prerequisite_task_id')
    )
    op.create_table('goal_root_tasks',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('goal_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['state_id', 'goal_id'], ['goals.state_id', 'goals.id'], name='fk_goal_root_tasks_goal_same_state'),
    sa.ForeignKeyConstraint(['state_id', 'task_id'], ['tasks.state_id', 'tasks.id'], name='fk_goal_root_tasks_task_same_state'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'goal_id', 'task_id'),
    sa.UniqueConstraint('state_id', 'task_id', name='uq_goal_root_tasks_task_per_state')
    )
    op.create_table('schedule_blocks',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=True),
    sa.Column('start_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('end_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('start_timestamp_microseconds < end_timestamp_microseconds', name='ck_schedule_blocks_valid_interval'),
    sa.ForeignKeyConstraint(['state_id', 'plan_id'], ['plans.state_id', 'plans.id'], name='fk_schedule_blocks_plan_same_state'),
    sa.ForeignKeyConstraint(['state_id', 'task_id'], ['tasks.state_id', 'tasks.id'], name='fk_schedule_blocks_task_same_state'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id'),
    sa.UniqueConstraint('state_id', 'task_id', 'id', name='uq_schedule_blocks_state_task_id')
    )
    op.create_table('observations',
    sa.Column('state_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('schedule_block_id', sa.Text(), nullable=False),
    sa.Column('actual_start_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('actual_end_timestamp_microseconds', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint('actual_start_timestamp_microseconds < actual_end_timestamp_microseconds', name='ck_observations_valid_interval'),
    sa.ForeignKeyConstraint(['state_id', 'task_id', 'schedule_block_id'], ['schedule_blocks.state_id', 'schedule_blocks.task_id', 'schedule_blocks.id'], name='fk_observations_schedule_block_same_task_and_state'),
    sa.ForeignKeyConstraint(['state_id'], ['planner_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('schedule_blocks')
    op.drop_table('goal_root_tasks')
    op.drop_table('dependencies')
    op.drop_table('tasks')
    op.drop_table('plans')
    op.drop_table('goals')
    op.drop_table('constraints')
    op.drop_table('calendar_events')
    op.drop_table('planner_states')
    # ### end Alembic commands ###
